### ISSUE TITLE
Editor threw error when a dataview codeblock in a callout block

### ISSUE THREAD

**Issue by BellTseng** [tadashi-aikawa/obsidian-embedded-code-title#10]
Thanks for your plugin.
I  tested on m1 Macos 12.3 , obsidian v.0.14.15 without any other plugins. 
I found if I wrote a dataview codeblock in a callout block. 

<img width="748" alt="image" src="https://user-images.githubusercontent.com/38106775/174532917-3cccc094-4951-408e-9639-1d20e94e8db8.png">

The editor would threw error, and I could not open the file unless i disabled this plugin. 

`Failed to load "Untitled.md". Cannot read properties of null (reading 'className')`

<img width="777" alt="image" src="https://user-images.githubusercontent.com/38106775/174532540-6c416c55-bb1d-4bd9-a5b0-22a0edaeab4c.png">

**Comment by tadashi-aikawa** [comment]
Hi, @BellTseng. Thank you for your bug report :)

I'll investigate it 👍

**Comment by tadashi-aikawa** [comment]
Fixed in [0.5.4](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/releases/tag/0.5.4) 🚀
