### ISSUE TITLE
Title block height overlaps code

### ISSUE THREAD

**Issue by jonasbirkelof** [tadashi-aikawa/obsidian-embedded-code-title#11]
The title/language block height is affected by the `.markdown-rendered` class from the Obsidian stylesheet, where it sets `min-height: 38px;`

![before](https://user-images.githubusercontent.com/61730892/196656592-1b5a30d3-86ec-432b-8f34-c6376d0117c6.png)

Obsidian version 1.0.0

I will make a PR with a fix.

**Comment by jonasbirkelof** [comment]
Please see Pull request #12 for a fix.

**Comment by tadashi-aikawa** [comment]
Released in [v0.5.5](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/releases/tag/0.5.5) 🚀
