### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Godamrit** [tadashi-aikawa/obsidian-embedded-code-title#13]
Hi, I was excited to use this plugin to title certain code blocks as I am learning programming right now but it doesn't seem to be working. Anything I write after the 1st 3 ticks will be rendered as the title, for example, the programming language but the colon will not let me embed a title in the code block. Anything I write after the colon doesn't appear as the title, and the programming language remains 

![image](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/120681852/1498c98d-ddd0-4afa-b307-203b9f006efb)

![image](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/120681852/431249b6-8753-43b6-b2e0-c90e71a25a9e)

**Comment by jonasbirkelof** [comment]
Just hit Enter after the first three ticks. 

```
Code here
```

**Comment by jonasbirkelof** [comment]
This is how it should be:

![image](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/61730892/fb06b99f-97d4-4a58-a53c-cbf66866c5fb)

![image](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/61730892/5d791c0c-e26e-4e74-a3d3-c7b3aab96706)

Try adding actual code, and maybe use `py` instead of `python`?

**Comment by Godamrit** [comment]
I'm a bit confused, what changes are you recommending I make? Also I did try it with actual code, it doesn't work. However, interestingly if I make a callout, that seems to render it but I don't want to have to make a callout each time 

![image](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/120681852/67d19b73-c189-4dfa-8740-e6f32cd28ea2)

![image](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/120681852/245408b2-3823-4385-b096-8443706373f4)

**Comment by jonasbirkelof** [comment]
Are you sure that you have the correct plugin activated? It's just that your example image in your first post doesn't look like how the plugin should. The language name should be in the top left corner and not to the right. Or are you using a theme that is messing things up? Try the default theme and see if that is the problem.

This is how it looks for me with the default theme:

![bild](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/61730892/ff3f4996-030b-4dc1-b04b-ddec3af6dfbb)

![bild](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/61730892/7ca5ad88-7f6c-46c5-a696-864e0f25294a)

![bild](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/assets/61730892/87903e0b-33d5-4422-8944-70f5b0e21feb)

**Comment by tadashi-aikawa** [comment]
@Godamrit 
Please see https://github.com/tadashi-aikawa/obsidian-embedded-code-title/issues/6. Maybe you expect that the plugin works on live preview mode. But not support it as far.

@jonasbirkelof 
Thanks for following!

**Comment by Godamrit** [comment]
Ah, so I have to put the notes in Reading Mode to see the changes! I was not aware that was required, thank you!
