### ISSUE TITLE
[FEAT] add an option to show the language name

### ISSUE THREAD

**Issue by yo-goto** [tadashi-aikawa/obsidian-embedded-code-title#2]
作った画像の右下の位置はちょっと適当なので左上でも右上でも良いですが、こんな感じでタイトルにファイル名を書かなくても使用している言語が分かるようにオプションとして表示してほしいです。

![language color](https://user-images.githubusercontent.com/50942816/125158514-ab548680-e1ac-11eb-98ea-55d38f10f287.png)

**Comment by tadashi-aikawa** [comment]
リクエストありがとうございます！

````
```python
def main():
    pass
```
````

の場合は `python` であることが分かるといい ということですね。オプションで検討してみます👍
