### ISSUE TITLE
[FEAT] please make it possible to use space characters in a code title

### ISSUE THREAD

**Issue by yo-goto** [tadashi-aikawa/obsidian-embedded-code-title#3]
コードタイトルにスペースを使えるようになると説明文を英単語まじりやコマンドでかけるようになるので機能追加の検討よろしくお願いします!

エディタ | プレビュー
---|---
<img width="379" alt="スクリーンショット 2021-07-17 1 30 10" src="https://user-images.githubusercontent.com/50942816/125979759-0938d499-a4c5-4697-b088-f98884f57a90.png"> | <img width="379" alt="スクリーンショット 2021-07-17 1 29 50" src="https://user-images.githubusercontent.com/50942816/125979773-24c6b22f-27fa-4367-8b72-8c6790e71441.png">

**Comment by tadashi-aikawa** [comment]
半角スペースはObsidian(CodeMirror?)が認識できなそうですので、特定の文字列を半角スペースに置換する設定を追加して対処してみます👍

**Comment by yo-goto** [comment]
ありがとうございます!
