### ISSUE TITLE
Title overlapping line

### ISSUE THREAD

**Issue by kzhovn** [tadashi-aikawa/obsidian-embedded-code-title#4]
On my theme (Atom), the title partially covers the first line: 
![Screenshot from 2021-08-03 17-32-16](https://user-images.githubusercontent.com/60860948/128089241-85cef8da-5b45-4ea1-9b97-226c2f8dd9a7.png)

A partial workaround might be to include the option to automatically insert an extra space into the codeblock, or at least render the background transparent to that the overlapping is less disruptive.

Great plugin, by the way, thank you! It's made labeling my codeblocks much easier.

**Comment by tadashi-aikawa** [comment]
Hi! @kzhovn. Thank you for reporting the issue.

I have confirmed to reproduce it. So I will fix it. 👍

**Comment by tadashi-aikawa** [comment]
📦 Release as [v0.5.1](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/releases/tag/0.5.1) ✨
