### ISSUE TITLE
Optimized for Light Theme

### ISSUE THREAD

**Issue by alexinea** [tadashi-aikawa/obsidian-embedded-code-title#5]
The current 0.5.1 version seems to be specially designed for dark mode only. In light mode, the effect is abrupt:

![image](https://user-images.githubusercontent.com/980129/132638010-7d6e7c37-9755-441b-b300-871120871120.png)

I will switch between different light and dark themes during the day and night. Can Embedded Code Title plug-in provide color configuration for the two modes? 

![image](https://user-images.githubusercontent.com/980129/132638183-dfe26d12-9230-4de5-bfcc-81c453411395.png)

Thx :)

**Comment by tadashi-aikawa** [comment]
Hi, @alexinea.

You can specify colors by [CSS snippets](https://help.obsidian.md/How+to/Add+custom+styles#Use+Themes+and+or+CSS+snippets) as follows.

```
/* Light theme */
.theme-light .obsidian-embedded-code-title__code-block-title {
  background-color: blue !important;
  color: darkgrey;
}

/* Dark theme */
.theme-dark .obsidian-embedded-code-title__code-block-title {
  background-color: red !important;
  color: darkgrey;
}
```

![image](https://user-images.githubusercontent.com/9500018/132972438-123fcc93-275c-4c9c-b367-e37a20ba6ba4.png)

![image](https://user-images.githubusercontent.com/9500018/132972433-e5c5112a-62e4-4cfa-a6bb-3759add61731.png)

Kind regards :)

**Comment by alexinea** [comment]
Thank you very much for your answers. (p≧w≦q)
