### ISSUE TITLE
syntax highlighting doesn't work 

### ISSUE THREAD

**Issue by pmatula** [tadashi-aikawa/obsidian-embedded-code-title#7]
Hi! 

As soon as you want to use the title in a code block, this works in principle, but the code is then no longer colored. 

I suppose that's the problem you wrote about what can happen when the internal DOM structure changes?

**Comment by tadashi-aikawa** [comment]
Hi, @pmatula :)

Sure, as you said, the latest version can't syntax highlight. I already fixed it in my local machine but didn't publish it yet, because it doesn't support Obsidian Publish.

However, I don't think it can get any worse than now, so I'll release it 👍

**Comment by pmatula** [comment]
Thanks @tadashi-aikawa !

**Comment by pmatula** [comment]
> @pmatula
> 
> Released [v0.5.3](https://github.com/tadashi-aikawa/obsidian-embedded-code-title/releases/tag/0.5.3) 🚀

Thanks for the quick solution.
